<a href="https://colab.research.google.com/github/BlackCode20146231/Machine-Learning/blob/main/CHAPTER_1_Vectors%2C_Matrices%2C_and_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.1 Creating a Vector

You need to create a vector.

Use NumPy to create a one-dimensional array:

In [20]:
# Load library
import numpy as np
# Create a vector as a row
vector_row = np.array([1, 2, 3])
# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])
print(vector_column)

matrix_column = np.array([[1,2,4],[2,4,5],[3,6,7]])
print('Matrix 3x3:\n',matrix_column)

[[1]
 [2]
 [3]]
Matrix 3x3:
 [[1 2 4]
 [2 4 5]
 [3 6 7]]


**Discussion**

# 1.2 Creating a Matrix

You need to create a matrix.

Use NumPy to create a two-dimensional array:

In [25]:
# Load library
import numpy as np
# Create a matrix
matrix = np.array([[1, 2],
 [1, 2],
 [1, 2]])
print(matrix)

[[1 2]
 [1 2]
 [1 2]]


**Discussion**

NumPy actually has a dedicated matrix data structure:

In [26]:
matrix_object = np.mat([[1, 2],
 [1, 2],
 [1, 2]])
print(matrix_object)

[[1 2]
 [1 2]
 [1 2]]


# 1.3 Creating a Sparse Matrix

Given data with very few nonzero values, you want to efficiently represent it.

Create a sparse matrix:

In [29]:
# Load libraries
import numpy as np
from scipy import sparse
# Create a matrix
matrix = np.array([[0, 0],
 [0, 1],
 [3, 0]])
# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)
# View sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [40]:
# Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
# View larger matrix
print(matrix_large)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]


In [41]:
# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)
# View original sparse matrix
print(matrix_sparse,'\n')
# View larger sparse matrix
print(matrix_large_sparse)


  (1, 1)	1
  (2, 0)	3 

  (1, 1)	1
  (2, 0)	3


# 1.4 Selecting Elements


You need to select one or more elements in a vector or matrix.

NumPy’s arrays make that easy:


In [43]:
# Load library
import numpy as np
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

In [44]:
# Select third element of vector
vector[2]

3

In [45]:
# Select second row, second column
matrix[1,1]

5

**Discussion**

In [46]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [47]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [48]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

In [49]:
# Select the last element
vector[-1]

6

In [50]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
# Select all rows and the second column
print(matrix,'\n')
matrix[:,1:2]

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



array([[2],
       [5],
       [8]])

# 1.5 Describing a Matrix

You want to describe the shape, size, and dimensions of the matrix.

Use shape, size, and ndim:

In [57]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]])

In [58]:
# View number of rows and columns
matrix.shape

(3, 4)

In [59]:
# View number of elements (rows * columns)
matrix.size

12

In [60]:
# View number of dimensions
matrix.ndim

2

# 1.6 Applying Operations to Elements

You want to apply some function to multiple elements in an array

Use NumPy’s vectorize:

In [61]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
# Create function that adds 100 to something
add_100 = lambda i: i + 100
# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)
# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

**Discussion**

    NumPy’s vectorize class converts a function into a function that can apply to all ele‐
    ments in an array or slice of an array. It’s worth noting that vectorize is essentially a
    for loop over the elements and does not increase performance.
    Furthermore, NumPy arrays allow us to perform operations between arrays even if their dimensions are not
    the same (a process called broadcasting). For example, we can create a much simpler
    version of our solution using broadcasting:

In [62]:
# Add 100 to all elements
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

# 1.7 Finding the Maximum and Minimum Values

You need to find the maximum or minimum value in an array.

Use NumPy’s max and min:

In [64]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
# Return maximum element
np.max(matrix)

9

In [68]:
# Return minimum element
print(matrix)
np.min(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


1

**Discussion**

    Often we want to know the maximum and minimum value in an array or subset of an
    array. This can be accomplished with the max and min methods. Using the axis
    parameter we can also apply the operation along a certain axis:

In [67]:
# Find maximum element in each column
print(matrix)
np.max(matrix, axis=0) #0 = each column

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([7, 8, 9])

In [69]:
# Find maximum element in each row
np.max(matrix, axis=1) #1 = each row

array([3, 6, 9])

# 1.8 Calculating the Average, Variance, and Standard Deviation

You want to calculate some descriptive statistics about an array

Use NumPy’s mean, var, and std:

In [70]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

In [71]:
# Return mean (trung bình có trọng số của tất cả các giá trị)
np.mean(matrix)

5.0

In [72]:
# Return variance (Phương sai)
np.var(matrix)

6.666666666666667

In [73]:
# Return standard deviation (Độ lệch chuẩn)
np.std(matrix)

2.581988897471611

**Discussion**

In [76]:
# Find the mean value in each column
np.mean(matrix, axis=0)


array([4., 5., 6.])

In [79]:
# Find the mean value in each row
np.mean(matrix, axis=1)


array([2., 5., 8.])

In [80]:
# Find the variance value in each column
np.var(matrix, axis=0)

array([6., 6., 6.])

In [81]:
# Find the variance value in each row
np.var(matrix, axis=1)

array([0.66666667, 0.66666667, 0.66666667])

In [78]:
# Find the standard deviation value in each column
np.std(matrix, axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [82]:
# Find the standard deviation value in each row
np.std(matrix, axis=1)

array([0.81649658, 0.81649658, 0.81649658])

# 1.9 Reshaping Arrays

You want to change the shape (number of rows and columns) of an array without
changing the element values.

Use NumPy’s reshape:

In [84]:
# Load library
import numpy as np
# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 [10, 11, 12]])
# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

**Discussion**

In [91]:
# We can see the size of a matrix using size
matrix.size

12

In [90]:
#reshape(-1, 1) means one row and as many columns as needed:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [92]:
#Finally, if we provide one integer, reshape will return a 1D array of that length:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# 1.10 Transposing a Vector or Matrix

You need to transpose a vector or matrix.

Use the T method:

In [93]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Discussion**

In [94]:
# Transpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [95]:
# Tranpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# 1.11 Flattening a Matrix (làm phẳng một ma trận)


You need to transform a matrix into a one-dimensional array

Use flatten:
gần giống 1.9 Reshaping Arrays
flatten is a simple method to transform a matrix into a one-dimensional array.
Alternatively, we can use reshape to create a row vector

In [99]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
#reshape(-1, 1) means one row and as many columns as needed:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# 1.12 Finding the Rank of a Matrix

You need to know the rank of a matrix.

    Trong đại số tuyến tính, hạng của một ma trận A 
    [_là số chiều của không gian vectơ được sinh bởi các vectơ cột của nó_] 
    Điều này tương đương với số cột độc lập tuyến tính tối đa của A,
    và như vậy, cũng chính là số chiều của không gian 
    vectơ sinh bởi các hàng của ma trận trên.

Use NumPy’s linear algebra method matrix_rank:

In [102]:
import numpy as np
# Create matrix
matrix = np.array([[1, 1, 1],
 [1, 1, 10],
 [1, 1, 15]])
# Return matrix rank
np.linalg.matrix_rank(matrix)

2

# 1.13 Calculating the Determinant (Định thức)



You need to know the determinant of a matrix.

Use NumPy’s linear algebra method det:

    Định thức, trong đại số tuyến tính, là một hàm cho mỗi ma trận vuông A, tương ứng với số vô hướng, ký hiệu là det.
    Ý nghĩa hình học của định thức là tỷ lệ xích cho thể tích khi A được coi là một biến đổi tuyến tính. 
    Định thức được sử dụng để giải các hệ phương trình đại số tuyến tính.

In [104]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [2, 4, 6],
 [3, 8, 9]])
# Return determinant of matrix
np.linalg.det(matrix)

0.0

# 1.14 Getting the Diagonal of a Matrix (Đường chéo)



You need to get the diagonal elements of a matrix.

Use diagonal

    Trong hình học, một đường chéo là một đoạn thẳng nối hai đỉnh của một đa giác hoặc đa diện,
    khi những đỉnh này không nằm trên cùng một cạnh. 
    Thông thường, bất kỳ đường không nằm ở mép nào cũng được gọi là đường chéo

    Trong đại số tuyến tính, một ma trận đường chéo là một ma trận trong đó các phần tử bên ngoài đường chéo chính đều bằng 0;
    thuật ngữ này thường đề cập đến ma trận vuông. Các phần tử của đường chéo chính có thể bằng không hoặc khác không.

In [105]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [2, 4, 6],
 [3, 8, 9]])
# Return diagonal elements
matrix.diagonal()

array([1, 4, 9])

In [106]:
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([2, 6])

In [107]:
# Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([2, 8])

# 1.15 Calculating the Trace of a Matrix



You need to calculate the trace of a matrix.

Use trace:

    Trong đại số tuyến tính, vết của một ma trận vuông A bậc nxn được xác định 
    bằng tổng các phần tử trên đường chéo chính của A

In [109]:
#Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [2, 4, 6],
 [3, 8, 9]])
# Return trace
matrix.trace()

14

In [110]:
# Return diagonal and sum elements
sum(matrix.diagonal())

14

# 1.16 Finding Eigenvalues and  (Giá trị riêng và vectơ riêng)

You need to find the eigenvalues and eigenvectors of a square matrix.

Use NumPy’s linalg.eig:





In [113]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, -1, 3],
 [1, 1, 6],
 [3, 8, 9]])
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
# View eigenvalues
eigenvalues


array([13.55075847,  0.74003145, -3.29078992])

In [114]:
# View eigenvectors
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

# 1.17 Calculating Dot Products



You need to calculate the dot product of two vectors.

Use NumPy’s dot:

In [117]:

# Load library
import numpy as np
# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
# Calculate dot product
np.dot(vector_a, vector_b)

32

In [118]:
# Calculate dot product
vector_a @ vector_b

32

# 1.18 Adding and Subtracting Matrices





You need to calculate the dot product of two vectors.

Use NumPy’s dot:

In [120]:
# Load library
import numpy as np
# Create matrix
matrix_a = np.array([[1, 1, 1],
 [1, 1, 1],
 [1, 1, 2]])

In [121]:
# Create matrix
matrix_b = np.array([[1, 3, 1],
 [1, 3, 1],
 [1, 3, 8]])

In [122]:
# Add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [123]:
# Subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

**Discussion**

In [124]:
# Add two matrices
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

# 1.19 Multiplying Matrices



You want to multiply two matrices

Use NumPy’s dot:

In [125]:
# Load library
import numpy as np
# Create matrix
matrix_a = np.array([[1, 1],
 [1, 2]])
# Create matrix
matrix_b = np.array([[1, 3],
 [1, 2]])

In [126]:
# Multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

**Discussion**

In [127]:
# Multiply two matrices
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [128]:
# Multiply two matrices element-wise (Nhân hai ma trận theo từng phần tử)
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

# 1.20 Inverting a Matrix (Đảo ngược ma trận)



You want to calculate the inverse of a square matrix.

Use NumPy’s linear algebra inv method:

In [129]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 4],
 [2, 5]])
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [130]:
# Multiply matrix and its inverse
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

# 1.21 Generating Random Values



You want to generate pseudorandom values

Use NumPy’s random:

In [131]:
# Load library
import numpy as np
# Set seed
np.random.seed(0)
# Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

**Discussion**

In [132]:
# Generate three random integers between 1 and 10
np.random.randint(0, 11, 3)

array([3, 7, 9])

In [133]:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [134]:
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3)

array([-0.98118713, -0.08939902,  1.46416405])

In [135]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.47997717, 1.3927848 , 1.83607876])